app/__init__.py
import os
import hashlib as hash
from flask import jsonify, request, redirect, url_for, Flask, render_template, g, send_from_directory, session
from flaskext.mysql import MySQL

app = Flask(__name__)

mysql = MySQL()

app.secret_key = b'1d f7 02 30 a2 ef 62 bb 41 50'
# MySQL configurations
app.config["MYSQL_DATABASE_USER"] = "root"
app.config["MYSQL_DATABASE_PASSWORD"] = os.getenv("db_root_password")
app.config["MYSQL_DATABASE_DB"] = os.getenv("db_name")
app.config["MYSQL_DATABASE_HOST"] = os.getenv("MYSQL_SERVICE_HOST")
app.config["MYSQL_DATABASE_PORT"] = int(os.getenv("MYSQL_SERVICE_PORT"))
mysql.init_app(app)

from . import auth, admin, ga, views
app.register_blueprint(auth.bp)
app.register_blueprint(admin.bp)
app.register_blueprint(ga.bp)
app.register_blueprint(views.bp)

@app.route("/")
def index():
    """Function to test the functionality of the API"""
    user_id = session.get('user_id')
    if user_id is None:
        return render_template('index.html')
    else:
        return redirect(url_for('userHome'))

@app.route("/demo")
def demo():
    return render_template('demo.html')

@app.route('/favicon.ico')
def favicon():
    return send_from_directory(os.path.join(app.root_path, 'static'),
                               'favicon.ico', mimetype='image/vnd.microsoft.icon')

@app.route('/userhome')
@auth.login_required
def userHome():
    num_ga = len(ga.getGAs())
    return render_template('userhome.html', num_ga = num_ga)

@app.errorhandler(401)
def unauthorized_page(error):
    return render_template("errors/401.html"), 401


@app.errorhandler(404)
def page_not_found(error):
    return render_template("errors/404.html"), 404


@app.errorhandler(500)
def server_error_page(error):
    return render_template("errors/500.html"), 500
   
#if __name__ == "__main__":
app.run(host="0.0.0.0", port=5000)

app/auth.py
import functools
import hashlib as hash
from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)

from app import mysql

bp = Blueprint('auth', __name__, url_prefix='/auth')

@bp.route('/login', methods=('GET', 'POST'))
def login():
    if request.method == 'POST':
        db = mysql.get_db().cursor()
        try:
            username = request.form['username']
            password = request.form['password']
        
            error = None
            db.execute(
                'SELECT * FROM USERS WHERE username = %s', (username,)
            )
            user = db.fetchone()
            
            if user is None:
                error = 'Incorrect username.'
                #return render_template('error.html',error = 'Wrong Username or Password')
            elif user[1] != hash.sha256(password.encode()).hexdigest():
                error = 'Incorrect password.'
                #return render_template('error.html',error = 'Wrong Username or Password')

            if error is None:
                session.clear()
                session['user_id'] = user[0]
                session['superuser'] = user[2]
                return redirect(url_for('index'))

            flash(error)
        except Exception as e:
            return render_template('errors/500.html',error = str(e))
        finally:
            db.close()

    return render_template('auth/login.html')

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    
    if user_id is None:
        g.user = None
    else:
        db = mysql.get_db().cursor()
        db.execute(
            'SELECT * FROM USERS WHERE username = %s', (user_id,)
        )
        g.user = db.fetchone()

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))

        return view(**kwargs)

    return wrapped_view

@bp.route('/logout')
@login_required
def logout():
    session.clear()
    flash("You were logged out.", "success")
    return redirect('/')

app/main.py
from app import app

app/views.py
import functools
import hashlib as hash
from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)
from flask import abort

from app import mysql
from app.auth import login_required
from app.ga import getGAs
import sys

bp = Blueprint('stats', __name__, url_prefix='/app')

# -----------------------------------------------------------------------------------------

'''
Types of Queries:
- Best individual from population: Given population id/ generation number, return the best individual
- Best individual from simulation: return best ind. from the highest generation number of a particular simulation
- a true login if given a username matches the associated password

- weights from individual
- Most recent pop / GA
- best fitness from each generation of simulation
'''

def best_nn_from_ga(gaID):
    '''
    gets the best individual from the genetic algorithm with the gaID given
    '''
    conn = mysql.connect()
    cursor = conn.cursor()

    query = "SELECT * FROM NEURAL_NETWORKS WHERE fitness IN ( \
        SELECT MAX(fitness) from NEURAL_NETWORKS WHERE nn_id IN ( \
            SELECT indiv_id FROM GENERATIONS WHERE pop_num IN (\
                SELECT generation_number from POPULATIONS WHERE fk_ga_id={gaID}}))) LIMIT 1;"
    cursor.execute(query)

    return cursor.fetchall()

    
def best_nn_from_pop(popID):
    '''
    gets all the individuals with the best score from the population of the given popID
    '''
    conn = mysql.connect()
    cursor = conn.cursor()

    query = "SELECT * FROM NEURAL_NETWORKS WHERE fitness IN (\
        SELECT MAX(fitness) from NEURAL_NETWORKS WHERE nn_id IN (\
            SELECT indiv_id FROM GENERATIONS WHERE pop_num={popID})) LIMIT 1;"
    cursor.execute(query)

    return cursor.fetchall()


def fitness_from_ga(gaID):
    '''
    gets the best fitness from each generation in a simulation
    '''
    conn = mysql.connect()
    cursor = conn.cursor()

    query = "SELECT fitness from NEURAL_NETWORKS WHERE nn_id IN ( \
        SELECT DISTINCT indiv_id FROM GENERATIONS WHERE pop_num IN (\
            SELECT generation_number from POPULATIONS WHERE fk_ga_id={gaID}})) ORDER BY nn_id;"
    cursor.execute(query)

    return cursor.fetchall()


#note: if the ID is passed in as an integer, do we need to convert this into a string int he query string?
def get_weights(id):
    '''
    gets the weights from an individual via individual specifing ID
    '''
    conn = mysql.connect()
    cursor = conn.cursor()

    query = "SELECT weights FROM individuals WHERE id ={id};"
    cursor.execute(query)

    return cursor.fetchall()

def get_maker(gaID):
    '''
    gets the best fitness from each generation in a simulation
    '''
    conn = mysql.connect()
    cursor = conn.cursor()

    query = "SELECT username from NEURAL_NETWORKS WHERE fk_ga_id={gaID}"
    cursor.execute(query)

    return cursor.fetchall()

    
@bp.route('stats')
@login_required
def stats():
    return render_template('ga/stats.html', GAs = getGAs())

app/templates/base.html
<!doctype html>
<html lang="en">
    <head>
        <title>{% block title %}{% endblock %} - Genetics Demo</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    </head>
    <body>
        <div class="container">		        
            <header class="header">             
                <nav 
                    class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom"
                >
                    <a
                        href="/"
                        class="text-dark text-decoration-none mb-3 mb-md-0 d-flex align-items-center me-md-auto"
                    >
                        <span class="fs-4">Genetics Demo</span>
                    </a>
                    <ul class="nav nav-pills justify-content-end">
                        {% if g.user %}
                            <li class="nav-item">
                                <a class="nav-link disabled" href="#">{{ g.user[0] }}</a>
                            </li>
                            <li class="nav-item">
                                <a href="/userhome" class="nav-link">Home</a>
                            </li>
                            <li class="nav-item">
                                <a href="{{ url_for('auth.logout') }}" class="nav-link active">Sign Out</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a href="/demo" class="nav-link">Request a Demo</a>
                            </li>
                            <li class="nav-item">
                                <a href="{{ url_for('auth.login') }}" class="nav-link active" aria-current="page">Sign In</a>
                            </li>
                        {% endif %}
                    </ul>                          
                </nav>             
            </header>
            <div class="container-fluid">
                {% for message in get_flashed_messages() %}
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endfor %}
            {% block content %}{% endblock %}
            </div>
            <footer class="footer">
				<p>&copy; CS 4604 Genetics29</p>
            </footer>
        </div>
    </body>
</html>

app/templates/demo.html
<!DOCTYPE html>
<html>
    <head>
    <meta http-equiv="refresh" content="0; URL=https://git.cs.vt.edu/genetics29/web-app" />
    </head>
</html>

app/templates/ga/runner.html
{% extends 'base.html' %}
{% block title %}Run Program{% endblock %}
{% block content %}
<div class="bg-light rounded-3 mb-4 p-5">
    <div class="container-fluid">
        <form method="post" action="/app/runner">
            <div class="form-group">
                <label for="select_ga">Select Algorithm</label>
                <select class="form-control" id="select_ga" name="ga_id">
                    {% for GA in GAs %}
                    <option value="{{ GA[0] }}"">
                        {{GA[2]}} Selection with {{GA[1]}} Crossover
                    </option>
                    {% endfor %}
                </select>
            </div>
            <button type="submit" class="btn btn-success">Run</button>
        </form>
    </div>
</div> 
{% endblock %}

app/templates/ga/stats.html
{% extends 'base.html' %}
{% block title %}Run Program{% endblock %}
{% block content %}
<div class="bg-light rounded-3 mb-4 p-5">
    <div class="container-fluid">
    </div>
</div> 
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block title %}Landing{% endblock %}

{% block content %}
<div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5 text-center">
        <h1 class="display-5 fw-bold">Train Neural Networks on a Genetic Algorithm!</h1>       
            <p>
                <a class="btn btn-lg btn-success" href="demo" role="button"
                    >Request a Demo</a
                >
            </p>
    </div>
</div>
{% endblock %}

app/templates/old/index_old.html
<!DOCTYPE html>
<html lang="en">
    <head>
		    
		<title>Genetics</title>
		    
		<link
			href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
			rel="stylesheet"
			integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
			crossorigin="anonymous"
		/>
		<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
	</head>
	<body>
		    

			        
			<div class="row marketing">
				            
				<div class="col-lg-6">
					                
					<h4>Bucket List</h4>
					                
					<p>
						Donec id elit non mi porta gravida at eget metus. Maecenas faucibus
						mollis interdum.
					</p>
					                                 
					<h4>Bucket List</h4>
					                
					<p>
						Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras
						mattis consectetur purus sit amet fermentum.
					</p>
					                
					<h4>Bucket List</h4>
					                
					<p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
					                
					<h4>Bucket List</h4>
					                
					<p>
						Donec id elit non mi porta gravida at eget metus. Maecenas faucibus
						mollis interdum.
					</p>
					                
					<h4>Bucket List</h4>
					                
					<p>
						Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras
						mattis consectetur purus sit amet fermentum.
					</p>
					                
					<h4>Bucket List</h4>
					                
					<p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
					            
				</div>
				        
			</div>
			        
			<footer class="footer">
				            
				<p>&copy; CS 4604 Genetics29</p>
				        
			</footer>
			    
		</div>
	</body>
</html>

app/templates/old/login_old.html
<!DOCTYPE html>
<html lang="en">
	<head>
		    
		<title>Genetics - Sign In</title>
		    
		<link
			href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
			rel="stylesheet"
			integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
			crossorigin="anonymous"
		/>
		<link href="../static/signup.css" rel="stylesheet" />
	</head>

	<body>
		    
		<div class="container">
			        
			<div class="header">
				            
				<nav
					class="border-bottom flex-wrap mb-4 py-3 d-flex justify-content-center"
				>
					<a
						href="/"
						class="text-dark text-decoration-none mb-3 mb-md-0 d-flex align-items-center me-md-auto"
					>
						<span class="fs-4">Genetics Demo</span>
					</a>

					<ul class="nav nav-pills">
						<li class="nav-item">
							<a href="/" class="nav-link">Home</a>
						</li>
						<li class="nav-item">
							<a href="/demo" class="nav-link">Request a Demo</a>
						</li>
						<li class="nav-item">
							<a href="/auth/login" class="nav-link active" aria-current="page"
								>Sign In</a
							>
						</li>
					</ul>
					                        
				</nav>
				        
			</div>
			<div class="bg-light rounded-3 mb-4 p-5">
				<div class="container-fluid py-5">
					<h1 class="text-center fw-bold display-5">Genetics App</h1>
					<form class="form-signin" action="/auth/login" method="post">
                        <label for="username" class="sr-only">Username</label>
                        <input type="username" name="username" id="username" class="form-control" placeholder="Username" required autofocus>
                        <label for="inputPassword" class="sr-only">Password</label>
                        <input type="password" name="password" id="password" class="form-control mb-2" placeholder="Password" required>

                        <button id="btnSignIn" class="btn btn-lg btn-primary btn-block " type="submit">Sign in</button>
                    </form>
			</div>
			        
			<footer class="footer">
				            
				<p>&copy; CS 4604 Genetics29</p>
				        
			</footer>

			    
		</div>

	</body>
</html>

app/templates/old/manage_ga.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
            crossorigin="anonymous"
        />
    <title>Genetic Algorithm Management CRUD Page</title>
  </head>
  <body>
    <h1>Genetic Algorithm Management</h1>
    <h2>Admin Interface</h2>
    <h3>Create GA</h3>
    <form method="POST" action="/create">
      <label for="max_generations">Max Generations:</label>
      <input type="number" name="max_generations" required /><br />
      <label for="selection">Selection:</label>
      <input type="text" name="selection" required /><br />
      <label for="crossover">Crossover:</label>
      <input type="text" name="crossover" required /><br />
      <label for="parent_amt">Parent Amount:</label>
      <input type="number" name="parent_amt" required /><br />
      <label for="elitist_amt">Elitist Amount:</label>
      <input type="number" name="elitist_amt" required /><br />
      <label for="mutation_scale">Mutation Scale:</label>
      <input type="number" name="mutation_scale" required /><br />
      <label for="mutation_rate">Mutation Rate:</label>
      <input type="number" name="mutation_rate" required /><br />
      <label for="population_count">Population Count:</label>
      <input type="number" name="population_count" required /><br />
      <button type="submit">Create GA</button>
    </form>
    <hr />

    <h3>Run GA</h3>
    <form method="POST" action="/run_simulation_admin">
      <label for="max_generations">Max Generations:</label>
      <input type="number" name="max_generations" required /><br />
      <label for="selection">Selection:</label>
      <input type="text" name="selection" required /><br />
      <label for="crossover">Crossover:</label>
      <input type="text" name="crossover" required /><br />
      <label for="parent_amt">Parent Amount:</label>
      <input type="number" name="parent_amt" required /><br />
      <label for="elitist_amt">Elitist Amount:</label>
      <input type="number" name="elitist_amt" required /><br />
      <label for="mutation_scale">Mutation Scale:</label>
      <input type="number" name="mutation_scale" required /><br />
      <label for="mutation_rate">Mutation Rate:</label>
      <input type="number" name="mutation_rate" required /><br />
      <label for="population_count">Population Count:</label>
      <input type="number" name="population_count" required /><br />
      <button type="submit">Run GA</button>
    </form>
    <hr />

    <!-- <h2>User Interface</h2>
    <h3>Create GA</h3>
    <form method="POST" action="/run_simulation_user">
      <label for="max_generations">Max Generations:</label>
      <input type="number" name="max_generations" required /><br />
      <label for="selection">Selection:</label>
      <input type="text" name="selection" required /><br />
      <label for="crossover">Crossover:</label>
      <input type="text" name="crossover" required /><br />
      <label for="parent_amt">Parent Amount:</label>
      <input type="number" name="parent_amt" required /><br />
      <label for="elitist_amt">Elitist Amount:</label>
      <input type="number" name="elitist_amt" required /><br />
      <label for="mutation_scale">Mutation Scale:</label>
      <input type="number" name="mutation_scale" required /><br />
      <label for="mutation_rate">Mutation Rate:</label>
      <input type="number" name="mutation_rate" required /><br />
      <label for="population_count">Population Count:</label>
      <input type="number" name="population_count" required /><br />
      <button type="submit">Create GA</button>
    </form>
    <hr /> --> 

app/templates/old/old_manage_ga.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Genetic Algorithm Management CRUD Page</title>
  </head>
  <body>
    <h1>Genetic Algorithm Management</h1>
    <h2>Admin Interface</h2>
    <h3>Create GA</h3>
    <form method="POST" action="/create">
      <label for="max_generations">Max Generations:</label>
      <input type="number" name="max_generations" required /><br />
      <label for="selection">Selection:</label>
      <input type="text" name="selection" required /><br />
      <label for="crossover">Crossover:</label>
      <input type="text" name="crossover" required /><br />
      <label for="parent_amt">Parent Amount:</label>
      <input type="number" name="parent_amt" required /><br />
      <label for="elitist_amt">Elitist Amount:</label>
      <input type="number" name="elitist_amt" required /><br />
      <label for="mutation_scale">Mutation Scale:</label>
      <input type="number" name="mutation_scale" required /><br />
      <label for="mutation_rate">Mutation Rate:</label>
      <input type="number" name="mutation_rate" required /><br />
      <label for="population_count">Population Count:</label>
      <input type="number" name="population_count" required /><br />
      <button type="submit">Create GA</button>
    </form>
    <hr />

    <h3>Best Individual from Population</h3>
    <p id="best-individual-from-population"></p>
    <button onclick="getBestIndividualFromPopulation()">Get Best Individual from Population</button>
    <script>
      function getBestIndividualFromPopulation() {
        var xhr = new XMLHttpRequest();
        xhr.onreadystatechange = function() {
          if (this.readyState == 4 && this.status == 200) {
            document.getElementById("best-individual-from-population").innerHTML = this.responseText;
          }
        };
        xhr.open("GET", "/best_individual_from_population", true);
        xhr.send();
      }
    </script>
    <hr />

    <h3>Run GA</h3>
    <form method="POST" action="/run_simulation_admin">
      <label for="max_generations">Max Generations:</label>
      <input type="number" name="max_generations" required /><br />
      <label for="selection">Selection:</label>
      <input type="text" name="selection" required /><br />
      <label for="crossover">Crossover:</label>
      <input type="text" name="crossover" required /><br />
      <label for="parent_amt">Parent Amount:</label>
      <input type="number" name="parent_amt" required /><br />
      <label for="elitist_amt">Elitist Amount:</label>
      <input type="number" name="elitist_amt" required /><br />
      <label for="mutation_scale">Mutation Scale:</label>
      <input type="number" name="mutation_scale" required /><br />
      <label for="mutation_rate">Mutation Rate:</label>
      <input type="number" name="mutation_rate" required /><br />
      <label for="population_count">Population Count:</label>
      <input type="number" name="population_count" required /><br />
      <button type="submit">Run GA</button>
    </form>
    <hr />

    </body>
</html>

app/templates/old/old_manage_users.html
<!DOCTYPE html>
<html>
<head>
	<title>Account Management</title>
	<link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
            crossorigin="anonymous"
        />
</head>
<body>
	<div class="container">
		<header class="header">
			<nav
					class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom"
				>
					<a
						href="/"
						class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none"
					>
						<span class="fs-4">Genetics Demo</span>
					</a>
					<ul class="nav nav-pills">
						<li class="nav-item">
							<a href="/" class="nav-link active" aria-current="page">Home</a>
						</li>
						<li class="nav-item">
							<a href="/auth/logout" class="nav-link">Logout</a>
						</li>
					</ul>
					                        
				</nav>
		</header>
		<div class="p-1 mb-4 bg-light rounded-3">
			<div class="container-fluid py-5 text-center">
				<h1 class="display-5 fw-bold">Account Management</h1>
			</div>
		

		</div>
	</div>

			<!-- Create Account Form -->
			<form method="POST" action="/create_account">
				<label for="username">Username:</label>
				<input type="text" id="username" name="username">
				<br>
				<label for="password">Password:</label>
				<input type="password" id="password" name="password">
				<br>
				<br>
				<button type="submit">Create Account</button>
			</form>

	<!-- Read Account Table -->
	<table>
		<tr>
			<th>ID</th>
			<th>Username</th>
			<th>Email</th>
			<th>Actions</th>
		</tr>
		{% for account in accounts %}
		<tr>
			<td>{{ account.id }}</td>
			<td>{{ account.username }}</td>
			<td>{{ account.email }}</td>
			<td>
				<a href="/edit_account/{{ account.id }}">Edit</a>
				<a href="/delete_account/{{ account.id }}">Delete</a>
			</td>
		</tr>
		{% endfor %}
	</table>

	<!-- Update Account Form -->
	<form method="POST" action="/update_account/{{ account.id }}">
		<label for="username">Username:</label>
		<input type="text" id="username" name="username" value="{{ account.username }}">
		<br>
		<label for="password">Password:</label>
		<input type="password" id="password" name="password" value="{{ account.password }}">
		<br>
		<label for="email">Email:</label>
		<input type="text" id="email" name="email" value="{{ account.email }}">
		<br>
		<button type="submit">Update Account</button>
	</form>

	<!-- Delete Account Form -->
	<form method="POST" action="/delete_account/{{ account.id }}">
		<p>Are you sure you want to delete this account?</p>
		<button type="submit">Yes</button>
		<button type="button" onclick="location.href='/accounts'">No</button>
	</form>

</body>
</html>

app/templates/userhome.html
{% extends 'base.html' %} {% block title %}Home{% endblock %} {% block content
%}
<div class="bg-light rounded-3 mb-4 p-5">
  <div class="container-fluid py-5">
    <h1 class="text-center fw-bold display-5">Welcome Back, {{g.user[0]}}!</h1>
    <br />
    <p class="text-primary text-center">
      Genetic Algorithms Active: {{num_ga}}
    </p>
  </div>
</div>

<div class="bg-light rounded-3 mb-4 p-5">
  <div class="container-fluid">
    <div class="row">
      {% if g.user[2] == 1 %}
      <div class="col-sm">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Manage Users</h5>
            <p class="card-text">Add, remove, or modify users.</p>
            <a
              href="{{ url_for('admin.manage_users') }}"
              class="btn btn-primary"
              >Go Here</a
            >
          </div>
        </div>
      </div>
      <div class="col-sm">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Manage Algorithms</h5>
            <p class="card-text">Create or Delete Genetic Algorithms</p>
            <a href="{{ url_for('admin.manage_algs') }}" class="btn btn-primary"
              >Go Here</a
            >
          </div>
        </div>
      </div>
      {% endif %}
      <div class="col-sm">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Run Algorithms</h5>
            <p class="card-text">Run an existing Genetic Algorithms.</p>
            <a href="{{ url_for('ga.run_algorithm') }}" class="btn btn-primary"
              >Go Here</a
            >
          </div>
        </div>
      </div>
      <div class="col-sm">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">View Statistics</h5>
            <p class="card-text">View common statistics of ran Algorithms.</p>
            <a href="{{ url_for('stats.stats') }}" class="btn btn-primary"
              >Go Here</a
            >
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}